export const COLOURS = Object.freeze({
  black: '#000000',
  brand: '#123524',
  brandDeep: '#0B271A',
  brandRaised: '#244838',
  brandMid: '#3F5E4E',
  brandMuted: '#6F877B',
  brandSoft: '#A6B8AE',
  sageStone: '#D8E2DC',
  paleSage: '#E8EFEB',
  mist: '#F4F7F5',
  white: '#FFFFFF',
  accent: '#43D9B1',
  accentHover: '#2FBF9D',
  accentMid: '#8BE7CF',
  accentLight: '#B0EEDD',
  accentXLight: '#C8F5E8',
  orange: '#F28C28',
  purple: '#A889FF',
  gold: '#D6B84C',
  leaf: '#8BC34A',
  pink: '#F06DB2',
  azure: '#4FA3D9',
  yellow: '#F2CF3A',
  peach: '#F39A78',
  red: '#E54865',
  error: '#C73552',
  errorSoft: '#FBE9EC',
  warning: '#D76500',
  warningSoft: '#FFF0DF',
  attention: '#A88400',
  attentionSoft: '#FFF8D8',
  success: '#3B8A55',
  successSoft: '#EAF5E7',
  info: '#23759D',
  infoSoft: '#E8F3F9',
});

export const CHART_SEQUENCE = Object.freeze([
  COLOURS.accent,
  COLOURS.orange,
  COLOURS.purple,
  COLOURS.gold,
  COLOURS.azure,
  COLOURS.pink,
  COLOURS.leaf,
  COLOURS.yellow,
  COLOURS.peach,
  COLOURS.red,
  COLOURS.white,
  COLOURS.sageStone,
]);

export const EDGE_COLOURS = Object.freeze({
  contains: COLOURS.brandSoft,
  references: COLOURS.accent,
  uses_defined_term: COLOURS.orange,
  defines: COLOURS.gold,
  shares_defined_term: COLOURS.azure,
  has_obligation_pattern: COLOURS.pink,
  shares_obligation_pattern: COLOURS.peach,
  has_structured_obligation: COLOURS.red,
  amends: COLOURS.error,
  has_permission: COLOURS.purple,
  has_version: COLOURS.purple,
  sourced_from: COLOURS.leaf,
  HAS_REGIME: COLOURS.azure,
  HAS_COLLECTION: COLOURS.accent,
  BELONGS_TO_REGIME: COLOURS.azure,
  BELONGS_TO_COLLECTION: COLOURS.accent,
  HAS_EDITION: COLOURS.gold,
  SUPERSEDES: COLOURS.brandSoft,
  HAS_TEMPLATE_RESOURCE: COLOURS.leaf,
  HAS_INSTRUCTION_RESOURCE: COLOURS.orange,
  HAS_RESOURCE: COLOURS.purple,
  CONTAINS_SHEET: COLOURS.azure,
  IMPLEMENTS_TEMPLATE: COLOURS.leaf,
  SUPPORTED_BY_TAXONOMY: COLOURS.purple,
  HAS_TAXONOMY_RESOURCE: COLOURS.purple,
  USES_TEMPLATE: COLOURS.accent,
  USES_INSTRUCTIONS: COLOURS.leaf,
  EVIDENCED_BY: COLOURS.purple,
  LEGAL_BASIS: COLOURS.error,
  APPLIES_TO: COLOURS.azure,
  HAS_SCOPE_RULE: COLOURS.accentMid,
  MAY_BE_AFFECTED_BY_PERMISSION: COLOURS.purple,
  REFERENCES_RULE: COLOURS.red,
  REFERENCES_SOURCE: COLOURS.purple,
  REFERENCES_EXTERNAL: COLOURS.brandSoft,
  REFERENCES_RETURN: COLOURS.peach,
  REFERENCES_TEMPLATE: COLOURS.gold,
  SUMMARISES_DATAPOINTS: COLOURS.gold,
  HAS_DATAPOINT: COLOURS.brandSoft,
  REPORTS_CONCEPT: COLOURS.azure,
});

export const MATERIAL_COLOURS = Object.freeze({
  rule: COLOURS.brandRaised,
  supervisory_statement: COLOURS.leaf,
  statement_of_policy: COLOURS.azure,
  definition: COLOURS.orange,
  permission: COLOURS.purple,
  external_reference: COLOURS.brandMuted,
  legal_instrument: COLOURS.red,
  obligation_pattern: COLOURS.pink,
  obligation_statement: COLOURS.red,
  analysis: COLOURS.purple,
  rulebook: COLOURS.gold,
  reporting_estate: COLOURS.sageStone,
  reporting_regime: COLOURS.azure,
  reporting_collection: COLOURS.accent,
  reporting_requirement: COLOURS.brandRaised,
  reporting_edition: COLOURS.gold,
  reporting_resource: COLOURS.purple,
  reporting_template: COLOURS.leaf,
  reporting_instruction: COLOURS.orange,
  reporting_source: COLOURS.azure,
  reporting_xbrl_source: COLOURS.purple,
  reporting_datapoint: COLOURS.brandSoft,
  reporting_provision: COLOURS.red,
  reporting_concept: COLOURS.azure,
});

export const CLUSTER_COLOURS = CHART_SEQUENCE.slice(0, 10);
