#!/usr/bin/env python3
from __future__ import annotations

import json
import shutil
import sqlite3
from datetime import datetime
from pathlib import Path

DB = Path(__file__).resolve().parents[1] / "backend/data/rulebook.sqlite3"
RUN_ID = "legacy_evidence_backfill_20260618"

DIRECT_TEXT_METHODS = {
    "html_link",
    "html_anchor_resolved",
    "html_anchor_unresolved",
    "html_glossary_link",
    "regex_reference",
    "regex_named_reference",
    "regex_article_reference",
    "resolved_part_reference",
    "rollup_resolved_part_reference",
    "llm_extracted_reference",
    "inline_part_definition",
    "structured_obligation_parser",
    "regex_obligation",
}
HTML_STRUCTURE_METHODS = {"site_structure", "pdf_text_extraction"}
DOCUMENT_METADATA_METHODS = {"glossary_source", "crr_terms_source", "legal_instrument_listing", "fca_waivers_list"}
INFERRED_METHODS = {"derived_term_overlap", "derived_obligation_overlap", "rollup_child_edge"}


def evidence_status(method: str, edge_type: str) -> str:
    if method in DIRECT_TEXT_METHODS:
        return "direct_text"
    if method in HTML_STRUCTURE_METHODS:
        return "html_structure"
    if method in DOCUMENT_METADATA_METHODS:
        return "document_metadata"
    if method in INFERRED_METHODS or edge_type.startswith("shares_"):
        return "inferred"
    return "missing"


def default_evidence(row: sqlite3.Row, status: str) -> str:
    edge_type = row["edge_type"]
    method = row["source_method"]
    source_title = row["source_title"] or row["from_node_id"]
    target_title = row["target_title"] or row["to_node_id"]
    if status == "html_structure":
        if edge_type == "contains":
            return f"HTML/document structure places '{target_title}' under '{source_title}'."
        return f"Relationship parsed from HTML/document structure by {method}."
    if status == "document_metadata":
        if edge_type == "defines":
            return f"Definition relationship from source metadata/listing: '{source_title}' defines '{target_title}'."
        return f"Relationship from source document metadata/listing by {method}."
    if status == "inferred":
        if edge_type == "shares_defined_term":
            return f"Inferred overlap: both nodes use one or more of the same defined terms."
        if edge_type == "shares_obligation_pattern":
            return f"Inferred overlap: both nodes share one or more obligation patterns."
        return f"Inferred analytical relationship generated by {method}."
    if status == "direct_text":
        return f"Direct textual relationship extracted by {method}."
    return "Evidence missing: legacy edge has no captured evidence text."


def main() -> None:
    ts = datetime.now().strftime("%Y%m%dT%H%M%S")
    backup = DB.with_name(f"rulebook.sqlite3.bak-edge-evidence-{ts}")
    shutil.copy2(DB, backup)

    conn = sqlite3.connect(DB, timeout=60)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA busy_timeout=60000")
    conn.execute("BEGIN IMMEDIATE")

    rows = conn.execute(
        """
        SELECT
          e.id,e.from_node_id,e.to_node_id,e.edge_type,e.source_method,e.confidence,
          e.evidence_text,e.source_url,e.metadata_json,
          s.title AS source_title,s.text AS source_text,s.url AS source_node_url,
          t.title AS target_title,t.text AS target_text,t.url AS target_node_url
        FROM edge e
        LEFT JOIN node s ON s.id=e.from_node_id
        LEFT JOIN node t ON t.id=e.to_node_id
        """
    ).fetchall()

    updated = 0
    status_counts: dict[str, int] = {}
    backfilled_evidence = 0
    backfilled_url = 0
    still_missing = 0

    for row in rows:
        meta = json.loads(row["metadata_json"] or "{}")
        status = meta.get("evidence_status") or evidence_status(row["source_method"], row["edge_type"])
        meta["evidence_status"] = status
        meta.setdefault("extraction_run_id", RUN_ID)
        status_counts[status] = status_counts.get(status, 0) + 1

        evidence_text = row["evidence_text"] or ""
        source_url = row["source_url"] or ""

        if not evidence_text:
            evidence_text = default_evidence(row, status)
            backfilled_evidence += 1
            meta["evidence_backfilled"] = True
        if not source_url:
            source_url = row["source_node_url"] or row["target_node_url"] or ""
            if source_url:
                backfilled_url += 1
                meta["source_url_backfilled"] = True
                if row["target_node_url"] and row["target_node_url"] != source_url:
                    meta.setdefault("target_url", row["target_node_url"])

        if status == "missing" or not source_url or not evidence_text:
            still_missing += 1

        conn.execute(
            "UPDATE edge SET evidence_text=?, source_url=?, metadata_json=? WHERE id=?",
            (evidence_text, source_url, json.dumps(meta, sort_keys=True, ensure_ascii=False), row["id"]),
        )
        updated += 1

    conn.commit()
    print(json.dumps({
        "backup": str(backup),
        "run_id": RUN_ID,
        "updated_edges": updated,
        "status_counts": status_counts,
        "backfilled_evidence_text": backfilled_evidence,
        "backfilled_source_url": backfilled_url,
        "still_missing_or_status_missing": still_missing,
    }, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
